version: 1.2.{build}
image: Visual Studio 2017
environment:
  DANGER_GITHUB_API_TOKEN:
    secure: i/HKbZ8JhJ2F2fHquUyevuCCx0nXEbWffqvlIqPfO6jcnfswZoXXqYMtvnN0u72K
cache:
  - ReSharperCLT2018.2.3
  - packages
  - vendor/bundler
install:
- cmd: >-
    set PATH=C:\Ruby25-x64\bin;%PATH%

    git submodule update --init --recursive

    nuget restore

    bundle install
- ps: >-
    if(![System.IO.Directory]::Exists((pwd).Path + "\ReSharperCLT2018.2.3")){
    
    Invoke-WebRequest -Uri https://download.jetbrains.com/resharper/ReSharperUltimate.2018.2.3/JetBrains.ReSharper.CommandLineTools.2018.2.3.zip -OutFile JetBrains.ReSharper.CommandLineTools.2018.2.3.zip

    Expand-Archive JetBrains.ReSharper.CommandLineTools.2018.2.3.zip -DestinationPath ReSharperCLT2018.2.3/

    }
before_build:
- cmd: >-
    dotnet sln remove iTunesNPPlugin\iTunesNPPlugin.csproj
    
    dotnet sln remove NowPlaying4Mac\NowPlaying4Mac.csproj
build:
  project: NowPlayingV2.sln
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
      - PluginTest
after_test:
- ps: >-
    ./ReSharperCLT2018.2.3/InspectCode.exe -o="report.xml" ./NowPlayingV2.sln

    bundle exec danger